# Datos de cada proyecto: fuente única para la galería y las fichas.
PROYECTOS = {
    "redes-piloto-automatico": {
        "titulo": "Mis redes se publican solas",
        "tipo": "Automatización",
        "chip": "cliente", "chip_texto": "Caso propio",
        "resumen": "Calendario, publicación automática en Instagram y LinkedIn, y un flujo de respaldo que comprueba que de verdad se publicó antes de avisar por correo.",
        "miniatura": "../../assets/redes/portada-caso.jpg",
        "problema": "Publicar cada día en redes quita una hora que no tengo, y un día saltado se nota. Necesitaba que saliera solo, sin depender de acordarme.",
        "hecho": [
            "Un calendario en el propio repositorio (48 carruseles programados, uno al día) que dispara la publicación en Instagram a través de GitHub Actions.",
            "Un publicador aparte para LinkedIn, con su propio calendario y registro, para que un fallo en una red no tumbe la otra.",
            "Un flujo de respaldo en n8n de 9 pasos: si el disparador principal se retrasa, este lo rescata, y solo avisa por correo después de comprobar que la publicación salió de verdad.",
            "Reintentos automáticos, freno propio para no publicar por error mientras se prueba, y aviso claro cuando un token de acceso está a punto de caducar.",
        ],
        "resultado": "Desde que está en marcha, la cuenta publica sola cada día. El único correo que llega es cuando algo necesita intervención — nunca uno de «todo bien», porque el silencio ya lo dice.",
        "cita": "El 10 de septiembre de 2026 el disparador de GitHub llegó con 67 minutos de retraso. El respaldo de n8n no existía todavía: se recuperó a mano. Es el caso real que hizo que se construyera el flujo de rescate.",
        "cta": "Quiero mis redes en piloto automático",
        "galeria": [
            {"src": "../../assets/redes/raw-github-actions-lista.jpg", "pie": "Historial de publicaciones automáticas en GitHub Actions."},
            {"src": "../../assets/redes/raw-n8n-flujo.jpg", "pie": "El flujo de respaldo en n8n: 9 pasos, con comprobación final antes de avisar."},
            {"src": "../../assets/redes/raw-instagram2.jpg", "pie": "La cuenta de Instagram, publicando sola cada día."},
        ],
    },
    "crm-energia": {
        "titulo": "CRM para consultoría energética",
        "tipo": "CRM a medida",
        "chip": "cliente", "chip_texto": "Cliente",
        "resumen": "Plataforma para varias asesorías energéticas a la vez: contratos, facturas revisadas y comisiones calculadas solas.",
        "miniatura": "../../assets/proyectos/crm.png",
        "problema": "Una consultoría que gestiona puntos de suministro para varios clientes necesitaba ver en un único sitio contratos, consumos y qué se puede ahorrar, sin mezclar los datos de una empresa con los de otra.",
        "hecho": [
            "Un panel que descarga las curvas de consumo y los precios de mercado automáticamente, y calcula el ahorro posible según la normativa vigente.",
            "Revisión automática de facturas para detectar excesos de potencia o energía reactiva.",
            "Cálculo y liquidación de comisiones para la red comercial.",
            "Cada empresa ve solo lo suyo: los datos están separados por políticas de la base de datos, no solo por pantalla.",
            "Cada cifra lleva una etiqueta de origen: real, calculada, estimada o simulada, para que nunca se confunda un dato de verdad con una previsión.",
        ],
        "resultado": "El equipo deja de cruzar hojas de cálculo a mano y ve, para cada cliente, qué vence, qué se puede ahorrar y qué hay que atender esta semana.",
        "cita": None,
        "cta": "Quiero un CRM así",
        "galeria": [
            {"src": "../../assets/proyectos/crm.png", "pie": "Panel de la empresa: cartera, contratos activos y vencimientos próximos."},
            {"src": "../../assets/proyectos/01-crm-b.png", "pie": "Licencias e integraciones con Datadis, OMIE, CNMC y SIPS, cada una con su estado."},
            {"src": "../../assets/proyectos/02-crm-b.png", "pie": "Buzón de alertas: qué vence, qué se puede ahorrar y qué hay que atender esta semana."},
            {"src": "../../assets/proyectos/03-crm-b.png", "pie": "Excesos de potencia y energía reactiva, con el origen de cada cifra etiquetado."},
        ],
    },
    "cantera": {
        "titulo": "Cantera — clubes de fútbol base",
        "tipo": "Plataforma de gestión",
        "chip": "cliente", "chip_texto": "Cliente",
        "resumen": "Cuotas, morosidad, plantilla por categoría y documentación con caducidad, en un panel que usa gente sin perfil técnico.",
        "miniatura": "../../assets/proyectos/cantera.png",
        "problema": "Un club de fútbol base llevaba las cuotas, las inscripciones y los papeles de cada niño en hojas sueltas. Nadie sabía, sin buscar, quién debía algo o a quién le caducaba un documento.",
        "hecho": [
            "Un panel con lo cobrado en el mes, la morosidad y las cuotas pendientes, pensado para directivas sin conocimientos técnicos.",
            "Plantilla organizada por categoría, con plazas ocupadas y libres a la vista.",
            "Documentación con fecha de caducidad, para que nadie juegue con un papel vencido sin que alguien lo note antes.",
            "Acceso separado para familias y para entrenadores, cada uno viendo solo lo que le corresponde.",
            "Los dos consentimientos de un menor — tratamiento de datos y derecho de imagen — se recogen por separado, como exige la normativa.",
        ],
        "resultado": "La directiva ve de un vistazo qué familias están al día, y la documentación de cada jugador deja de perderse entre carpetas.",
        "cita": None,
        "cta": "Quiero un panel así",
        "galeria": [
            {"src": "../../assets/proyectos/cantera.png", "pie": "Panel del club: cobrado en el mes, morosidad y cuotas pendientes."},
            {"src": "../../assets/proyectos/01-cantera-b.png", "pie": "Evolución de lo cobrado a lo largo de la temporada."},
            {"src": "../../assets/proyectos/02-cantera-b.png", "pie": "Plantilla por categoría, con las plazas ocupadas y las libres."},
            {"src": "../../assets/proyectos/03-cantera-b.png", "pie": "Últimas inscripciones y documentación con fecha de caducidad."},
        ],
    },
    "distail": {
        "titulo": "Distail — recepción y captación con IA",
        "tipo": "Arquitectura de agente",
        "chip": "cliente", "chip_texto": "Cliente",
        "resumen": "Diseño de qué resuelve un agente conversacional al atender una llamada y qué resuelve un flujo determinista al crear la cita.",
        "miniatura": "../../assets/proyectos/distail.png",
        "problema": "El cliente quería atender llamadas con un agente de voz, pero necesitaba saber, con seguridad, qué parte podía dejarse a la conversación y qué parte tenía que quedar fija para no fallar nunca.",
        "hecho": [
            "Reparto explícito de responsabilidades: qué contesta el agente conversacional y qué ejecuta un flujo con reglas fijas.",
            "El recorrido completo de una llamada entrante, desde que suena el teléfono hasta que la cita queda creada en la agenda y el CRM actualizado.",
            "El motivo de cada decisión de diseño, documentado junto a la propia decisión, no aparte.",
            "Entregado como guía visual y como presentación, para que el cliente pueda auditar el sistema que está financiando.",
        ],
        "resultado": "El cliente sabe exactamente qué hace el agente por su cuenta y qué no, antes de poner un euro en producción.",
        "cita": None,
        "cta": "Quiero una arquitectura así",
        "galeria": [
            {"src": "../../assets/proyectos/distail.png", "pie": "Arquitectura general: qué resuelve un agente y qué resuelve un flujo."},
            {"src": "../../assets/proyectos/01-distail-b.png", "pie": "Reparto de responsabilidades entre el agente conversacional y la automatización."},
            {"src": "../../assets/proyectos/02-distail-b.png", "pie": "Recorrido de una llamada entrante hasta la cita creada en la agenda."},
            {"src": "../../assets/proyectos/03-distail-b.png", "pie": "Captación saliente y seguimiento posterior en el CRM."},
        ],
        "videos": [
            {"src": "../../assets/video/distail-arquitectura.mp4", "poster": "../../assets/video/distail-arquitectura-poster.jpg", "titulo": "La arquitectura explicada"},
            {"src": "../../assets/video/distail-precision.mp4", "poster": "../../assets/video/distail-precision-poster.jpg", "titulo": "Precisión de la captación"},
        ],
    },
    "rustik": {
        "titulo": "Rustik Gastro Bar — carta y reservas",
        "tipo": "Web y panel",
        "chip": "cliente", "chip_texto": "Cliente",
        "resumen": "Sitio del restaurante con carta, galería y reserva de mesa, más un panel para que el propio negocio la actualice sin intermediarios.",
        "miniatura": "../../assets/proyectos/rustik.png",
        "problema": "La carta cambiaba a menudo y cada cambio significaba llamar a alguien para que tocara la web. El negocio quería poder editarla ellos mismos.",
        "hecho": [
            "Web con carta por secciones, galería, carta descargable y reserva de mesa con día, hora y número de comensales.",
            "Panel de administración para que el propio negocio actualice platos y precios sin intermediarios.",
            "Los datos de la carta residen en un archivo propio del cliente: se edita y se publica, sin pasar por un desarrollador cada vez.",
        ],
        "resultado": "El restaurante actualiza su carta el mismo día que cambia, sin depender de nadie más.",
        "cita": None,
        "cta": "Quiero una web así",
        "galeria": [
            {"src": "../../assets/proyectos/rustik.png", "pie": "Portada del restaurante."},
            {"src": "../../assets/proyectos/01-rustik-b.png", "pie": "Carta por secciones, editable desde el panel del negocio."},
            {"src": "../../assets/proyectos/02-rustik-b.png", "pie": "Galería del local."},
            {"src": "../../assets/proyectos/03-rustik-b.png", "pie": "Reserva de mesa con día, hora y número de comensales."},
        ],
    },
    "facturetool": {
        "titulo": "FactureTool — facturación para autónomos",
        "tipo": "Aplicación web",
        "chip": "propia", "chip_texto": "Herramienta propia",
        "resumen": "Emisión de facturas con numeración correlativa y resumen por trimestres listo para la gestoría, sin servidor que mantener.",
        "miniatura": "../../assets/proyectos/facturetool.png",
        "problema": "Herramienta propia, nacida de la misma necesidad que tiene cualquier autónomo: facturar rápido y llegar al trimestre con los números ya ordenados.",
        "hecho": [
            "Emisión de facturas con numeración correlativa y vencimientos automáticos.",
            "Resumen por trimestres con exportación para la gestoría: IVA repercutido para el modelo 303 y retenciones para el 130.",
            "Separación clara entre facturas emitidas y borradores.",
            "Funciona íntegramente en el navegador, sin servidor ni base de datos que mantener.",
        ],
        "resultado": "Es la prueba de que una herramienta simple, sin servidor, puede ahorrar el trabajo manual de cada trimestre.",
        "cita": None,
        "cta": "Quiero algo así para mi negocio",
        "galeria": [
            {"src": "../../assets/proyectos/facturetool.png", "pie": "Nueva factura, con numeración correlativa y vencimiento automático."},
            {"src": "../../assets/proyectos/01-facturetool-b.png", "pie": "Listado de facturas, con su estado de cobro."},
            {"src": "../../assets/proyectos/02-facturetool-b.png", "pie": "Resumen por trimestres y exportación para la gestoría."},
            {"src": "../../assets/proyectos/03-facturetool-b.png", "pie": "Configuración, copias de seguridad y registro de emisión."},
        ],
    },
    "barbershop": {
        "titulo": "Barber Shop — cita online en tres pasos",
        "tipo": "Reservas",
        "chip": "demo", "chip_texto": "Demostración",
        "resumen": "Selección de servicios, duración y precio antes de confirmar, con acceso de administración para el negocio.",
        "miniatura": "../../assets/proyectos/barbershop.png",
        "problema": "Pieza de demostración, sobre datos de ejemplo pero con el catálogo de servicios real del sector: para negocios que hoy gestionan la agenda por mensajería.",
        "hecho": [
            "Selección de varios servicios en la misma cita, con duración y precio visibles antes de confirmar.",
            "Elección de día y profesional según la agenda real del local.",
            "Acceso de administración: agenda del día, servicios y empleados.",
        ],
        "resultado": "Sirve para que un negocio de este tipo vea, antes de contratar nada, cómo quedaría su propia agenda online.",
        "cita": None,
        "cta": "Quiero algo así para mi negocio",
        "galeria": [
            {"src": "../../assets/proyectos/barbershop.png", "pie": "Elección de servicios, con duración y precio a la vista."},
            {"src": "../../assets/proyectos/01-barbershop-b.png", "pie": "Elección del día entre los disponibles."},
            {"src": "../../assets/proyectos/02-barbershop-b.png", "pie": "Profesional y hora, según la agenda real del local."},
            {"src": "../../assets/proyectos/03-barbershop-b.png", "pie": "Acceso de administración: agenda del día, servicios y empleados."},
        ],
    },
}
